model: AD
num_actions: 6
seed: 42
dataset_root: datasets
mixed_precision: bf16

tf_n_embd: 256
tf_n_layer: 6
tf_n_head: 8
tf_dim_feedforward: 1024
tf_dropout: 0.1
cnn_depth: 32
n_transit: 256
label_smoothing: 0.0

lr: 0.0003
beta1: 0.9
beta2: 0.95
weight_decay: 0.01
grad_clip: 1.0
train_batch_size: 32
test_batch_size: 32
train_timesteps: 100000
num_warmup_steps: 2000
checkpoint_interval: 5000
num_workers: 4
dataset_stride: 8
