include: config/model/rad_dr.yaml

latent_update_mode: gru_gate
latent_gru_init_bias: -2.0
run_name: RAD-darkroom-seed0-gru_gate
pretrain_run_name: RAD-pretrain-darkroom-seed0
experiment_name: rad_latent_update_comparison
