include: config/model/ad_base.yaml

model: RAD

# Compression Transformer (must match rad_ml1.yaml)
tf_n_embd: 64
tf_n_layer: 4
tf_n_head: 8
tf_dropout: 0.1
tf_attn_dropout: 0.1
tf_n_inner: 1024
tf_dim_feedforward: 1024
n_transit: 100


# Dataset settings
min_context_length: 120
max_context_length: 2500
rad_batching_strategy: compression_buckets

# Compression Settings (must match rad_ml1.yaml)
n_compress_tokens: 60
always_use_latent_prefix: True
short_memory_keep: 20

compress_n_layers: 4
compress_n_heads: 4

# Pre-training specific
pretrain_timesteps: 50000
pretrain_batch_size: 256
pretrain_lr: 0.0003
pretrain_warmup_steps: 3000

# Dataset
train_source_timesteps: 2500
train_n_seed: 50
train_n_stream: 100

torch_compile: True
torch_compile_modules:
  - compression_transformer
  - reconstruction_decoder
torch_compile_mode: reduce-overhead
torch_compile_dynamic: True
torch_compile_fullgraph: False
torch_compile_suppress_errors: True

num_workers: 4
